/** All player-facing words. Chinese first. No cinema voice. */
export const copy = {
  brand: "NumbahWan",
  gameZh: "楓之谷：閒置英雄",
  gameEn: "MapleStory: Idle RPG",
  loaderZh: "載入中",
  loaderEn: "Loading",
  scrollZh: "往下看",
  scrollEn: "Scroll",
  joinZh: "自由加入",
  joinEn: "Join Freely",
  joinShortZh: "加入",
  joinShortEn: "Join",
  signInZh: "登入",
  signInEn: "Sign in",
  guildZh: "公會",
  guildEn: "Guild",
  masterZh: "會長",
  masterEn: "Master",
  avgZh: "平均等級",
  avgEn: "Avg Lv",
  conquestZh: "征服戰",
  conquestEn: "Conquest",
  joinWayZh: "加入方式",
  joinWayEn: "Join",
  xpZh: "公會經驗",
  xpEn: "Guild XP",
  seatsZh: "想來就來，不用審核。",
  seatsEn: "Open roster. No approval.",
  ctaZh: "想來就來，不用審核。",
  ctaEn: "Open roster. No approval.",
  applyZh: "申請加入",
  applyEn: "Apply",
  ignZh: "角色名稱",
  ignEn: "Character name",
  classZh: "職業",
  classEn: "Class",
  noteZh: "給會長的話",
  noteEn: "Note to master",
  optionalZh: "選填",
  optionalEn: "Optional",
  sendZh: "送出",
  sendEn: "Send",
  sendingZh: "送出中…",
  sendingEn: "Sending…",
  doneZh: "收到了，遊戲裡見。",
  doneEn: "Got it. See you in-game.",
  closeZh: "關閉",
  closeEn: "Close",
  errZh: "出了點問題",
  errEn: "Something broke",
  reloadZh: "重新整理再試一次。",
  reloadEn: "Reload and try again.",
  loginLeadZh: "用你平常的帳號進來。",
  loginEn: "Use the account you already have.",
  continueZh: "使用",
  continueEn: "Continue with",
  noticeZh: "NumbahWan No.1 中央大會 12月24日",
  noticeEn: "No.1 Central Assembly · Dec 24",
  disabledZh: "登入未開放。",
  disabledEn: "Sign-in is off.",
  ignErrZh: "角色名稱至少 2 個字。",
  ignErrEn: "Name needs at least 2 characters.",
  wallZh: "成員",
  wallEn: "Members",
  wallLeadZh: "滑看 24 張。每人一張。",
  wallLeadEn: "24 cards. One each.",
  foundersZh: "會長 · 副書記",
  foundersEn: "Master · Vice",
  masterRoleZh: "總書記",
  masterRoleEn: "Master",
  viceRoleZh: "副書記",
  viceRoleEn: "Vice",
  prevZh: "上一張",
  prevEn: "Previous",
  nextZh: "下一張",
  nextEn: "Next",
} as const;

export const classes = [
  { id: "Warrior", zh: "戰士", en: "Warrior" },
  { id: "Mage", zh: "法師", en: "Mage" },
  { id: "Archer", zh: "弓箭手", en: "Archer" },
  { id: "Thief", zh: "盜賊", en: "Thief" },
  { id: "Pirate", zh: "海盜", en: "Pirate" },
  { id: "Hybrid", zh: "複合", en: "Hybrid" },
] as const;
